"""prueba2we

Revision ID: 277c9bbe63dc
Revises: 3d7dd2b9a34a
Create Date: 2024-06-24 10:28:11.258945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277c9bbe63dc'
down_revision: Union[str, None] = '3d7dd2b9a34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
